export const Strings = {
    registration: "Registration",
    enter_first_name: "Enter First Name",
    save: "Save",
    cancel: "Cancel",
    male: "Male",
    female: "Female",
    patient_id: "Patient id",
    patient_num: "Patient number",
    first_name: "First Name",
    last_name: "Last Name",
    birth_place: "Place of birth",
    nearest_birth_place: "Nearest birth place",
    enter_age: "Enter age",
    birth_Date: "Birth Date",
    birth_time: "Birth Time",
    address: "Address",
    state: "State",
    district: "District",
    select_option: "Select Option",
    gender: "Gender",
    male: "Male",
    female: "Female",
    radioButtonVal: "RadioButtonVal",
    please_enter_value: "Please enter value",
    please_select_one: "Please select one",
    first_visit: "First visit",
    ph_num: "Enter Mobile number",
    edit: "Edit",
    delete: "Delete",
    update: "Update",
    city: "City"

}